package inventory

import (
	"context"
	"errors"
	"testing"
	"time"
)

// fakeStore satisfies both ProductStore and SalesStore from in-memory maps.
//
// Hand-written rather than generated by a mocking library, and that is a
// deliberate choice worth defending: this is about thirty lines, it has no
// dependency, and it reads as ordinary Go. Mock frameworks earn their keep when
// you need call-order assertions across a wide interface; here they would add a
// dependency and a DSL to learn in exchange for nothing.
//
// It also proves the point of the ports: the domain is fully testable with no
// Postgres, no Docker and no build tag.
type fakeStore struct {
	products map[string]*Product
	sales    map[string][]SalesDay

	// Error injection, so the failure paths are reachable in a unit test.
	getProductErr error
	getHistoryErr error
	recordErr     error

	// Call counting, to prove the batch path does not fan out into N queries.
	getProductsCalls  int
	getHistoriesCalls int
}

func newFakeStore() *fakeStore {
	return &fakeStore{
		products: make(map[string]*Product),
		sales:    make(map[string][]SalesDay),
	}
}

func (f *fakeStore) GetProduct(_ context.Context, sku string) (*Product, error) {
	if f.getProductErr != nil {
		return nil, f.getProductErr
	}
	p, ok := f.products[sku]
	if !ok {
		return nil, ErrProductNotFound
	}
	return p, nil
}

func (f *fakeStore) GetProducts(_ context.Context, skus []string) (map[string]*Product, error) {
	f.getProductsCalls++
	out := make(map[string]*Product)
	for _, sku := range skus {
		if p, ok := f.products[sku]; ok {
			out[sku] = p
		}
	}
	return out, nil
}

func (f *fakeStore) GetSalesHistory(_ context.Context, sku string, since time.Time) ([]SalesDay, error) {
	if f.getHistoryErr != nil {
		return nil, f.getHistoryErr
	}
	return filterSince(f.sales[sku], since), nil
}

func (f *fakeStore) GetSalesHistories(_ context.Context, skus []string, since time.Time) (map[string][]SalesDay, error) {
	f.getHistoriesCalls++
	out := make(map[string][]SalesDay)
	for _, sku := range skus {
		if days := filterSince(f.sales[sku], since); len(days) > 0 {
			out[sku] = days
		}
	}
	return out, nil
}

func (f *fakeStore) RecordSalesDay(_ context.Context, sku string, day SalesDay) error {
	if f.recordErr != nil {
		return f.recordErr
	}
	f.sales[sku] = append(f.sales[sku], day)
	return nil
}

func filterSince(days []SalesDay, since time.Time) []SalesDay {
	var out []SalesDay
	for _, d := range days {
		if !d.Date.Before(since) {
			out = append(out, d)
		}
	}
	return out
}

// fixedClock freezes time so history-window arithmetic is deterministic.
func fixedClock(t time.Time) func() time.Time { return func() time.Time { return t } }

// serviceFixture builds a Service over a fake store holding one healthy SKU
// with 28 days of steady sales.
func serviceFixture(t *testing.T) (*Service, *fakeStore) {
	t.Helper()

	store := newFakeStore()
	store.products["MILK-1L"] = &Product{
		SKU:                "MILK-1L",
		Name:               "Whole Milk 1L",
		LeadTimeDays:       3,
		ReviewPeriodDays:   1,
		CaseSize:           12,
		TargetServiceLevel: 1.65,
		OnHandUnits:        10,
	}
	// Sales run up to the day before "now" so every day sits inside the window.
	for i := 0; i < 28; i++ {
		store.sales["MILK-1L"] = append(store.sales["MILK-1L"], SalesDay{
			Date:      anchor.AddDate(0, 0, i),
			UnitsSold: 20,
		})
	}

	svc := NewService(store, store, DefaultConfig()).
		WithClock(fixedClock(anchor.AddDate(0, 0, 28)))
	return svc, store
}

func TestServiceRecommend(t *testing.T) {
	svc, _ := serviceFixture(t)

	rec, err := svc.Recommend(context.Background(), "MILK-1L")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if rec.SKU != "MILK-1L" {
		t.Errorf("SKU = %q, want MILK-1L", rec.SKU)
	}
	// avg 20/day, lead 3, review 1, sigma 0 => target 80, position 10 => 70,
	// rounded up to 72 on a 12-unit case.
	if rec.RecommendedQuantity != 72 {
		t.Errorf("RecommendedQuantity = %d, want 72", rec.RecommendedQuantity)
	}
}

func TestServiceRecommend_Errors(t *testing.T) {
	sentinel := errors.New("database exploded")

	tests := []struct {
		name    string
		sku     string
		setup   func(*fakeStore)
		wantErr error
	}{
		{
			name:    "unknown sku",
			sku:     "NOPE",
			setup:   func(*fakeStore) {},
			wantErr: ErrProductNotFound,
		},
		{
			name:    "product lookup fails",
			sku:     "MILK-1L",
			setup:   func(f *fakeStore) { f.getProductErr = sentinel },
			wantErr: sentinel,
		},
		{
			name:    "history lookup fails",
			sku:     "MILK-1L",
			setup:   func(f *fakeStore) { f.getHistoryErr = sentinel },
			wantErr: sentinel,
		},
		{
			name: "sku with no sales history",
			sku:  "MILK-1L",
			setup: func(f *fakeStore) {
				f.sales["MILK-1L"] = nil
			},
			wantErr: ErrEmptySalesHistory,
		},
		{
			name: "sku whose history is entirely stockouts",
			sku:  "MILK-1L",
			setup: func(f *fakeStore) {
				for i := range f.sales["MILK-1L"] {
					f.sales["MILK-1L"][i].StockOutOccurred = true
				}
			},
			wantErr: ErrInsufficientHistory,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			svc, store := serviceFixture(t)
			tt.setup(store)

			_, err := svc.Recommend(context.Background(), tt.sku)
			// errors.Is walks the %w chain, so this passes even though Recommend
			// wraps the store error with "load sales history for MILK-1L: ...".
			// That is exactly why the wrapping verb matters: context is added
			// without destroying the identity the caller matches on.
			if !errors.Is(err, tt.wantErr) {
				t.Fatalf("got error %v, want %v", err, tt.wantErr)
			}
		})
	}
}

func TestServiceRecommendBatch(t *testing.T) {
	svc, store := serviceFixture(t)

	// A second, slow-moving SKU and a third that does not exist.
	store.products["CAVIAR-50G"] = &Product{
		SKU:                "CAVIAR-50G",
		Name:               "Caviar 50g",
		LeadTimeDays:       7,
		ReviewPeriodDays:   1,
		CaseSize:           1,
		TargetServiceLevel: 1.65,
		OnHandUnits:        4,
	}
	for i := 0; i < 28; i++ {
		store.sales["CAVIAR-50G"] = append(store.sales["CAVIAR-50G"], SalesDay{
			Date: anchor.AddDate(0, 0, i), UnitsSold: 0,
		})
	}

	results, err := svc.RecommendBatch(context.Background(),
		[]string{"MILK-1L", "CAVIAR-50G", "GHOST-SKU"})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if len(results) != 3 {
		t.Fatalf("got %d results, want 3", len(results))
	}

	t.Run("results preserve request order", func(t *testing.T) {
		want := []string{"MILK-1L", "CAVIAR-50G", "GHOST-SKU"}
		for i, sku := range want {
			if results[i].SKU != sku {
				t.Errorf("results[%d].SKU = %q, want %q", i, results[i].SKU, sku)
			}
		}
	})

	t.Run("one bad sku does not sink the batch", func(t *testing.T) {
		if results[0].Recommendation == nil {
			t.Error("MILK-1L has no recommendation")
		}
		if results[2].Error == "" {
			t.Error("GHOST-SKU should carry an error")
		}
		if results[2].Recommendation != nil {
			t.Error("GHOST-SKU should not carry a recommendation")
		}
	})

	t.Run("batch issues one query per store, not one per sku", func(t *testing.T) {
		// The N+1 guard. Without the batch store methods this would be 3 and 3,
		// and at DashMart scale — a few thousand SKUs per replenishment run —
		// that is the difference between one round trip and several thousand.
		if store.getProductsCalls != 1 {
			t.Errorf("GetProducts called %d times, want 1", store.getProductsCalls)
		}
		if store.getHistoriesCalls != 1 {
			t.Errorf("GetSalesHistories called %d times, want 1", store.getHistoriesCalls)
		}
	})
}

func TestServiceRecommendBatch_EmptyRequest(t *testing.T) {
	svc, _ := serviceFixture(t)

	_, err := svc.RecommendBatch(context.Background(), nil)
	if !errors.Is(err, ErrNoProducts) {
		t.Fatalf("got error %v, want ErrNoProducts", err)
	}
}

func TestServiceRecordSale(t *testing.T) {
	tests := []struct {
		name    string
		sku     string
		day     SalesDay
		setup   func(*fakeStore)
		wantErr error
	}{
		{
			name:  "records a valid day",
			sku:   "MILK-1L",
			day:   SalesDay{Date: anchor, UnitsSold: 25},
			setup: func(*fakeStore) {},
		},
		{
			name:    "unknown sku is a not-found, not a constraint violation",
			sku:     "GHOST",
			day:     SalesDay{Date: anchor, UnitsSold: 25},
			setup:   func(*fakeStore) {},
			wantErr: ErrProductNotFound,
		},
		{
			name:    "negative units rejected",
			sku:     "MILK-1L",
			day:     SalesDay{Date: anchor, UnitsSold: -5},
			setup:   func(*fakeStore) {},
			wantErr: ErrInvalidProduct,
		},
		{
			name:    "store failure is wrapped and surfaced",
			sku:     "MILK-1L",
			day:     SalesDay{Date: anchor, UnitsSold: 25},
			setup:   func(f *fakeStore) { f.recordErr = errors.New("write failed") },
			wantErr: nil, // asserted separately below
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			svc, store := serviceFixture(t)
			tt.setup(store)

			err := svc.RecordSale(context.Background(), tt.sku, tt.day)

			switch {
			case tt.wantErr != nil:
				if !errors.Is(err, tt.wantErr) {
					t.Fatalf("got error %v, want %v", err, tt.wantErr)
				}
			case store.recordErr != nil:
				if err == nil {
					t.Fatal("expected the store failure to surface")
				}
			default:
				if err != nil {
					t.Fatalf("unexpected error: %v", err)
				}
			}
		})
	}
}

func TestServiceHistoryCutoff(t *testing.T) {
	// The cutoff must reach back further than the estimation window, so a run of
	// stockouts at the start does not leave too few uncensored days.
	now := anchor.AddDate(0, 0, 100)
	svc := NewService(newFakeStore(), newFakeStore(), Config{HistoryWindowDays: 28, Alpha: 0.1}).
		WithClock(fixedClock(now))

	got := svc.historyCutoff()
	want := now.AddDate(0, 0, -(28 + historyFetchSlackDays))

	if !got.Equal(want) {
		t.Errorf("historyCutoff() = %v, want %v", got, want)
	}
	if !got.Before(now.AddDate(0, 0, -28)) {
		t.Error("cutoff does not reach beyond the estimation window")
	}
}

func TestNewServiceNormalisesConfig(t *testing.T) {
	tests := []struct {
		name       string
		in         Config
		wantWindow int
		wantAlpha  float64
	}{
		{name: "zero values fall back to defaults", in: Config{},
			wantWindow: DefaultHistoryWindowDays, wantAlpha: DefaultAlpha},
		{name: "negative window falls back", in: Config{HistoryWindowDays: -1, Alpha: 0.2},
			wantWindow: DefaultHistoryWindowDays, wantAlpha: 0.2},
		{name: "alpha above one falls back", in: Config{HistoryWindowDays: 14, Alpha: 5},
			wantWindow: 14, wantAlpha: DefaultAlpha},
		{name: "valid config is preserved", in: Config{HistoryWindowDays: 14, Alpha: 0.25},
			wantWindow: 14, wantAlpha: 0.25},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			svc := NewService(newFakeStore(), newFakeStore(), tt.in)
			if svc.cfg.HistoryWindowDays != tt.wantWindow {
				t.Errorf("HistoryWindowDays = %d, want %d", svc.cfg.HistoryWindowDays, tt.wantWindow)
			}
			if !floatEq(svc.cfg.Alpha, tt.wantAlpha, 1e-9) {
				t.Errorf("Alpha = %v, want %v", svc.cfg.Alpha, tt.wantAlpha)
			}
		})
	}
}
